package com.syncmind.android.ui.theme

import androidx.compose.ui.graphics.Color

val SyncPrimary = Color(0xFF0058BE)
val SyncPrimaryContainer = Color(0xFFD8E2FF)
val SyncOnPrimaryContainer = Color(0xFF001A42)
val SyncSecondary = Color(0xFF565E74)
val SyncSecondaryContainer = Color(0xFFDAE2FD)
val SyncTertiary = Color(0xFF4F5D6E)
val SyncTertiaryContainer = Color(0xFFD5E4F8)
val SyncBackground = Color(0xFFF8F9FF)
val SyncSurface = Color(0xFFFFFFFF)
val SyncSurfaceLow = Color(0xFFEFF4FF)
val SyncSurfaceContainer = Color(0xFFE5EEFF)
val SyncSurfaceHigh = Color(0xFFDCE9FF)
val SyncOnSurface = Color(0xFF0B1C30)
val SyncOnSurfaceVariant = Color(0xFF424754)
val SyncOutline = Color(0xFF727785)
val SyncOutlineVariant = Color(0xFFC2C6D6)
val SyncError = Color(0xFFBA1A1A)
val SyncErrorContainer = Color(0xFFFFDAD6)

val SyncDarkPrimary = Color(0xFFADC6FF)
val SyncDarkBackground = Color(0xFF0B1524)
val SyncDarkSurface = Color(0xFF142033)
val SyncDarkSurfaceContainer = Color(0xFF213145)
val SyncDarkOnSurface = Color(0xFFEAF1FF)
val SyncDarkOnSurfaceVariant = Color(0xFFBEC6D9)

val StatusOpen = Color(0xFF64748B)
val StatusInProgress = Color(0xFF3B82F6)
val StatusResolved = Color(0xFF10B981)
val StatusClosed = Color(0xFF0F172A)
val PriorityLow = Color(0xFF94A3B8)
val PriorityNormal = Color(0xFF3B82F6)
val PriorityHigh = Color(0xFFEF4444)
